# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from visier_authentication_python_sdk import VisierAuthentication

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        visierauthentication = VisierAuthentication(
        
                        api_key_auth = 'YOUR_API_KEY',
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD'
        )
        self.assertIsNotNone(visierauthentication)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
