# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_authentication_python_sdk.paths.v1_admin_visier_secure_token.post import ASidTokenAuthenticationRaw
from visier_authentication_python_sdk.paths.v1_auth_oauth2_authorize.get import OAuth2AuthorizeRaw
from visier_authentication_python_sdk.paths.v1_auth_oauth2_token.post import OAuth2TokenRaw
from visier_authentication_python_sdk.paths.v1_admin_visier_secure_ticket.post import TicketAuthenticationRaw


class AuthenticationApiRaw(
    ASidTokenAuthenticationRaw,
    OAuth2AuthorizeRaw,
    OAuth2TokenRaw,
    TicketAuthenticationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
