# coding: utf-8
"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_authentication_python_sdk.client_custom import ClientCustom
from visier_authentication_python_sdk.configuration import Configuration
from visier_authentication_python_sdk.api_client import ApiClient
from visier_authentication_python_sdk.type_util import copy_signature
from visier_authentication_python_sdk.apis.tags.authentication_api import AuthenticationApi



class VisierAuthentication(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.authentication: AuthenticationApi = AuthenticationApi(api_client)
