# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_authentication_python_sdk
from visier_authentication_python_sdk.model.authentication_o_auth2_token200_response import AuthenticationOAuth2Token200Response
from visier_authentication_python_sdk import configuration


class TestAuthenticationOAuth2Token200Response(unittest.TestCase):
    """AuthenticationOAuth2Token200Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
