# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_authentication_python_sdk
from visier_authentication_python_sdk.model.google_protobuf_any import GoogleProtobufAny
from visier_authentication_python_sdk import configuration


class TestGoogleProtobufAny(unittest.TestCase):
    """GoogleProtobufAny unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
