# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_authentication_python_sdk
from visier_authentication_python_sdk.model.authentication_asid_token_authentication200_response import AuthenticationAsidTokenAuthentication200Response
from visier_authentication_python_sdk import configuration


class TestAuthenticationAsidTokenAuthentication200Response(unittest.TestCase):
    """AuthenticationAsidTokenAuthentication200Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
