# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTokenRequestBody(TypedDict):
    pass

class OptionalTokenRequestBody(TypedDict, total=False):
    # The grant type. Supported values: - `authorization_code`: The authorization code grant type. - `password`: The password grant type. - `urn:visier:params:oauth:grant-type:asid-token`: The ASID token grant type.
    grant_type: str

    # The ID of the pre-registered client application.
    client_id: str

    # The optional URI to redirect to after authorization.
    redirect_uri: str

    # The authorization code. Applicable only for authorization code grant type.
    code: str

    # The username of the user to authenticate. Applicable only for password grant type.
    username: str

    # The password of the user to authenticate. Applicable only for password grant type.
    password: str

    # The ASID token. Applicable only for ASID token grant type.
    asid_token: str

class TokenRequestBody(RequiredTokenRequestBody, OptionalTokenRequestBody):
    pass
