# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_authentication_python_sdk.pydantic.google_protobuf_any import GoogleProtobufAny

class Status(BaseModel):
    # The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
    code: typing.Optional[int] = Field(None, alias='code')

    # The error message returned by the server.
    message: typing.Optional[str] = Field(None, alias='message')

    # A list of messages that carry the error details.  There is a common set of message types for APIs to use.
    details: typing.Optional[typing.List[GoogleProtobufAny]] = Field(None, alias='details')
    class Config:
        arbitrary_types_allowed = True
